// Wave 1 — differential test: every entry in the Wave 0 scanner corpus must
// produce the SAME observable Scan output through the new
// `tool/shell/scan.ts` `scanCommand` + `askForScan` pipeline.
//
// The corpus was generated by running the LEGACY `tool/shell.ts` scanner
// against each command and capturing the FIRST `ctx.ask` payload (sentinel
// throw on first ask — see `test/fixtures/generate-corpus.ts`). To compare
// like-for-like, this test reproduces that capture pattern: drive
// `scanCommand` to get the Scan struct, then call `askForScan` with a ctx
// that throws on first ask, and compare the captured request to the corpus's
// `expected_*` fields.
//
// Single mismatch on any entry = wave failure. Surgical diffs allowed only
// if explicitly enumerated in NOTES.md per `TDD.md` § "Differential testing".

import { afterEach, describe, expect } from "bun:test"
import { Effect, Layer } from "effect"
import { CrossSpawnSpawner } from "@opencode-ai/core/cross-spawn-spawner"
import { AppFileSystem } from "@opencode-ai/core/filesystem"
import { Plugin } from "@/plugin"
import { Shell } from "@/shell/shell"
import { InstanceState } from "@/effect/instance-state"
import { ShellScan } from "@/tool/shell/scan"
import * as Tool from "@/tool/tool"
import type { Permission } from "@/permission"
import { MessageID, SessionID } from "@/session/schema"
import { disposeAllInstances } from "../fixture/fixture"
import { loadScannerCorpus } from "../fixtures/load-config"
import { testEffect } from "../lib/effect"

afterEach(async () => {
  await disposeAllInstances()
})

const it = testEffect(
  Layer.mergeAll(
    AppFileSystem.defaultLayer,
    CrossSpawnSpawner.defaultLayer,
    Plugin.defaultLayer,
  ),
)

const defaultShell = Shell.acceptable()

type CapturedRequest = Omit<Permission.Request, "id" | "sessionID" | "tool">

const SENTINEL = new Error("__diff_stop__")

function captureCtx(): { requests: CapturedRequest[]; ctx: Tool.Context } {
  const requests: CapturedRequest[] = []
  const ctx: Tool.Context = {
    sessionID: SessionID.make("ses_diff"),
    messageID: MessageID.make(""),
    callID: "",
    agent: "build",
    abort: AbortSignal.any([]),
    messages: [],
    metadata: () => Effect.void,
    ask: (req) =>
      Effect.sync(() => {
        requests.push(req)
        throw SENTINEL
      }),
  }
  return { requests, ctx }
}

const sortedUnique = (arr: ReadonlyArray<string>) => Array.from(new Set(arr)).sort()
const dirFromGlob = (g: string) => g.replace(/[/\\]\*$/, "")

describe("differential — scanner-extract preserves bash-ask payloads against corpus", () => {
  it.instance("every corpus command produces matching ask payloads", () =>
    Effect.gen(function* () {
      const corpus = yield* Effect.promise(() => loadScannerCorpus())
      const instance = yield* InstanceState.context

      const failures: string[] = []

      for (const entry of corpus) {
        const scan = yield* ShellScan.scanCommand({
          command: entry.cmd,
          shell: defaultShell,
          cwd: instance.directory,
          instance,
        })
        const { requests, ctx } = captureCtx()
        // SENTINEL throws inside ask; suppress and keep the captured first
        // request. Mirrors generate-corpus.ts try/catch pattern.
        yield* ShellScan.askForScan(ctx, scan).pipe(Effect.catchCause(() => Effect.void))

        const bashReq = requests.find((r) => r.permission === "bash")
        const extReq = requests.find((r) => r.permission === "external_directory")

        const got = {
          patterns: bashReq ? sortedUnique([...bashReq.patterns]) : [],
          always: bashReq ? sortedUnique([...bashReq.always]) : [],
          dirs: extReq ? sortedUnique([...extReq.patterns].map(dirFromGlob)) : [],
        }
        const expected = {
          patterns: [...entry.expected_patterns].sort(),
          always: [...entry.expected_always].sort(),
          dirs: [...entry.expected_dirs].sort(),
        }

        if (
          JSON.stringify(got.patterns) !== JSON.stringify(expected.patterns) ||
          JSON.stringify(got.always) !== JSON.stringify(expected.always) ||
          JSON.stringify(got.dirs) !== JSON.stringify(expected.dirs)
        ) {
          failures.push(
            `cmd=${JSON.stringify(entry.cmd)}\n  expected=${JSON.stringify(expected)}\n  got=${JSON.stringify(got)}`,
          )
        }
      }

      if (failures.length > 0) {
        throw new Error(`${failures.length} corpus entries diverged:\n${failures.join("\n")}`)
      }
      expect(failures.length).toBe(0)
    }),
  )
})
